
<link href='%TEMPLATEURL%/css/default.css' rel='stylesheet' type='text/css' />
<link href='%TEMPLATEURL%/css/jquery.datepick.css' rel='stylesheet' type='text/css' />
<!--<link href='%TEMPLATEURL%/css/jquery.autocomplete.css' rel='stylesheet' type='text/css' /> -->
<link href='%TEMPLATEURL%/css/simpleModal.css' rel='stylesheet' type='text/css' />
<link href='%TEMPLATEURL%/css/codemirror.css' rel='stylesheet' type='text/css' />
<link rel='shortcut icon' href='%TEMPLATEURL%/images/favicon.ico' type='image/x-icon' />
<script language='JavaScript' src='%TEMPLATEURL%/js/jquery-1.10.2.min.js' type='text/javascript'></script>
<script language='JavaScript' src='%TEMPLATEURL%/js/jquery-ui-1.10.3.custom.min.js' type='text/javascript'></script>
<script language='JavaScript' src='%TEMPLATEURL%/js/jquery.datepick.min.js' type='text/javascript'></script>
<script language='JavaScript' src='%TEMPLATEURL%/js/jquery.datetimepicker.js' type='text/javascript'></script>
<script language='JavaScript' src='%TEMPLATEURL%/js/jquery-tableclass.js' type='text/javascript'></script>
<script language='JavaScript' src='%TEMPLATEURL%/js/jquery.address-1.5.min.js' type='text/javascript'></script>
<script language='JavaScript' src='%TEMPLATEURL%/js/jquery.maskedinput.js' type='text/javascript'></script>
<script language='JavaScript' src='%TEMPLATEURL%/js/codemirror-compressed.js'></script>
<script language='JavaScript' src='%TEMPLATEURL%/js/jquery.simplemodal.1.4.4.min.js' type='text/javascript'></script>


